config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'
  
  # routes welcome
  get 'welcome/privacidad'
  get 'welcome/terminos'
  
  # route user_form_firebase
  get 'user_form_firebase/user_form'

  get 'user_form_firebase/changeFormStatus'

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }


  # routes user profile
  get 'user_profile/index'
  get 'user_profile/ajustes'
  get 'user_profile/validacion'
  get 'user_profile/update'
  get 'user_profile/ayuda'
  get 'user_profile/ficha'
  get 'user_profile/gFicha'
  get 'user_profile/rFicha'
  get 'user_profile/promotores'
  
  # routes admin_panel
  get 'admin_panel/index', path: 'admin_panel'
  get 'admin_panel/validacion'
  get 'admin_panel/reportes'
  get 'admin_panel/ayuda'
  get 'admin_panel/validar'
  get 'admin_panel/rechazar'
  get 'admin_panel/email'
  get 'admin_panel/showData'
  get 'admin_panel/usuarios'
  get 'admin_panel/promotores'
  
  
  resources :user_profile
  resources :user_settings
end

app/models/ability.rb
class Ability
  include CanCan::Ability
 
  def initialize(user)
    # Define abilities for the passed in user here. For example:
 
    user ||= User.new # guest user (not logged in)
    if user.superadmin_role?
      can :manage, :all
    end
    if user.supervisor_role?
      can :manage, User
    end
    
  end
end

app/models/arbol1.rb
class Arbol1 < ActiveRecord::Base

end

app/models/arbol2.rb
class Arbol2 < ActiveRecord::Base
end

app/models/arbol3.rb
class Arbol3 < ActiveRecord::Base
end

app/models/arbol4.rb
class Arbol4 < ActiveRecord::Base
end

app/models/p1.rb
class P1 < ActiveRecord::Base
end

app/models/p2.rb
class P2 < ActiveRecord::Base
end

app/models/p3.rb
class P3 < ActiveRecord::Base
end

app/models/p4.rb
class P4 < ActiveRecord::Base
end

app/models/payment.rb
class Payment < ActiveRecord::Base


    validates :avatar,
    attachment_content_type: { content_type: /\Aimage\/.*\Z/ },
    attachment_size: { less_than: 15.megabytes }

  has_attached_file :avatar,
    :storage => :cloudinary,
    :path => "payments/:filename",
    :styles => {
      :thumb => '600x600>',
      :square => '800x800#',
      :medium => '1200x1200>'
    }
end

app/models/user.rb
class User < ActiveRecord::Base
  
 
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable #, :confirmable
         
   validates :avatar,
    attachment_content_type: { content_type: /\Aimage\/.*\Z/ },
    attachment_size: { less_than: 15.megabytes }

  has_attached_file :avatar,
    :storage => :cloudinary,
    :path => "avatar/:filename",
    :styles => {
      :thumb => '600x600>',
      :square => '800x800#',
      :medium => '1200x1200>'
    }
end

app/controllers/admin_panel_controller.rb
class AdminPanelController < ApplicationController
        #before_action :rol, only: [:index,:validacion,:validar,:reportes,:ayuda, :rechazar]

    def index
        @p1 = Arbol1.all
        @p2 = Arbol2.all
        @p3 = Arbol3.all
        @p4 = Arbol4.all
        
       
        
        
        render 'principal'
        
    end
    
    def validacion
        @payments = Payment.where.not(:avatar_file_name => nil, :status => true, :rechazado => true)
        
    end
    
    def email
        id = params[:user_id]
        @email = User.find(id)
        render json: @email
    end
    
    def reportes
        render 'reportes'
    end
    
    def ayuda
        render 'ayuda'
    end
    
    def promotores
        render 'promotores'
    end
    
    def usuarios
        @users = User.all
        render 'usuarios'
    end
    
    def validar
        id = params[:payment_id]
        tipo = params[:tipo_paquete]
        payment = Payment.find(id)
	user_id = payment.user_id
            if payment.update(status: true)
                 if posicionar(id,tipo,user_id)
                     redirect_to admin_panel_validacion_path
                 else
                     render  inline: tipo
                 end
                 
            else
                    
            end
       
    end
    
    def showData

            user_id = params[:user_id]
            tipo_paquete = params[:tipo_paquete]
            @payments = Payment.where(user_id: user_id, tipo_paquete: tipo_paquete).select(:id, :user_id,:tipo_paquete, :created_at)
             render json: @payments
        
    end
    
    def rechazar
        id = params[:payment_id]
        payment = Payment.find(id)
            if payment.update(rechazado: true)

                     redirect_to admin_panel_validacion_path
                 
            else
                    redirect_to 
            end
    end
    
    
    
    private
    
    def rol
        if ((user_signed_in?)&&(current_user.supervisor_role == true))
            
        else
            @notice = true
            redirect_to root_path, :flash => { :Error => "Aun no has inciado sesión" }
        end
    end
    
    def posicionar(id,tipo,user_id)
        
        case tipo
        when "1"
            posant = Arbol1.last
            
            if posant == nil
                ant = 1
            else
                ant = posant.posicion
            ant += 1
            end
            posicion = Arbol1.create(user_id: user_id , posicion: ant, payment_id: id)
            if posicion.save
                return true
            end
        
    
        
        
        when "2"
            posant = Arbol2.last
            
            if posant== nil
                ant = 1
            else
                ant = posant.posicion
                ant += 1
            end
            posicion = Arbol2.create(user_id: user_id, posicion: ant, payment_id: id)
            if posicion.save
                return true
            end
        
        
         when "3"
             posant = Arbol3.last
            
            if posant == nil
                ant = 1
            else
                    ant = posant.posicion
                    ant += 1
                
            end
            posicion = Arbol3.create(user_id: user_id, posicion: ant, payment_id: id)
            if posicion.save
                return true
            end
        
        
         when "4"
             posant = Arbol4.last
            
            if posant == nil
                ant = 1
            else
                ant = posant.posicion
            ant += 1
            end
            posicion = Arbol4.create(user_id: user_id, posicion: ant, payment_id: id)
            if posicion.save
                return true
            end
        else
            return false
        end
    end
    
    
    

    
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
  private
    
    def after_inactive_sign_up_path_for(resource_or_scope)
      root_path
    end
    
    # Overwriting the sign_in, redirect path to user form for firebase
    def after_sign_in_path_for(resource_or_scope)
      if(current_user.firebase_form === false)
        user_form_firebase_user_form_path
      else
        if(current_user.supervisor_role === true)
          admin_panel_index_path
        else
          user_profile_index_path
        end
      end
    end

end

app/controllers/session_controller.rb
class SessionController < ApplicationController
    def index
        
    end
    
    def new 
        
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  before_action :user, only: [:index,:terminos,:privacidad]
  def user
        if current_user
        
        @id = current_user.id
        end
  end

  def index
    
    
  end
  
  def terminos
    render 'terminos'
  end
  
  def privacidad
    render 'privacidad'
  end
  

end

app/helpers/admin_panel_helper.rb
module AdminPanelHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/session_helper.rb
module SessionHelper
end

app/helpers/user_form_firebase_helper.rb
module UserFormFirebaseHelper
end

app/helpers/user_profile_helper.rb
module UserProfileHelper
end

app/helpers/user_settings_helper.rb
module UserSettingsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/admin_panel/ayuda.html.erb
<div id="page-content-wrapper">
    <div class="page-content">
        <div class="container-fluid">
                <div class="row" style="margin-top: 70px;">
                    <div class="col-md-offset-1">
                        <div class="col-md-11">
                            <h1 class="text-center" style="color: #004467;"><strong>MENSAJES AYUDA</strong></h1>
                                
                                <div class="col-md-12">
                                <div class="table-responsive">
                                      <table id="mytable" class="table table-bordred table-striped table-hover">
                              
                              <thead>
                            <tr style="background-color: #2c3e50; color: white;">
                            <th><input type="checkbox" id="checkall" /></th>
                            <th>Nombre</th>
                            <th>Apellido</th>
                            <th>Asunto</th>
                            <th>Correo Electrónico</th>
                            <th>Teléfono Fijo</th>
                            <th>Fecha</th>
                            <th>Mensaje</th>
                            <th>Responder</th>
                            <th>Eliminar</th>
                            </tr>
                             </thead>
                            <tbody>
                            
                            <tr>
                            <td><input type="checkbox" class="checkthis" /></td>
                            <td>Hugo Arnoldo</td>
                            <td>Gutierrez</td>
                            <td>Problemas</td>
                            <td>hugo@fidei.mx</td>
                            <td>12/12/12</td>
                            <td>3333333332</td>
                            <td><p data-placement="top" data-toggle="tooltip" title="Edit"><button class="btn btn-info btn-xs" data-title="Edit" data-toggle="modal" data-target="#Mensaje" ><span class="glyphicon glyphicon-envelope"></span></button></p></td>
                            <td><p data-placement="top" data-toggle="tooltip" title="Edit"><button class="btn btn-primary btn-xs" data-title="Edit" data-toggle="modal" data-target="#edit" ><span class="glyphicon glyphicon-pencil"></span></button></p></td>
                            <td><p data-placement="top" data-toggle="tooltip" title="Delete"><button class="btn btn-danger btn-xs" data-title="Delete" data-toggle="modal" data-target="#delete" ><span class="glyphicon glyphicon-trash"></span></button></p></td>
                            </tr>
                            
                           
                            
                            </tbody>
                                
                        </table>
                                        
                                    </div>
                                    
                                </div>
                        
                        <div class="modal fade" id="Mensaje" tabindex="-1" role="dialog" aria-labelledby="edit" aria-hidden="true">
                              <div class="modal-dialog">
                            <div class="modal-content">
                                  <div class="modal-header">
                                <button type="button" class="close" data-dismiss="modal" aria-hidden="true"><span class="glyphicon glyphicon-remove" aria-hidden="true"></span></button>
                                <h4 class="modal-title custom_align" id="Heading">Mensaje de Ayuda</h4>
                              </div>
                                <div class="modal-body">
                                <div class="form-group">
                                <label>Nombre:</label>
                                <input class="form-control " type="text" value="Hugo Arnoldo Gutierrez" disabled>
                                </div>
                                <div class="form-group">
                                <label>Asunto:</label>
                                <input class="form-control " type="text" value="Tengo problemas con mi Cuenta" disabled>
                                </div>
                                <div class="form-group">
                                <label>Mensaje:</label>
                                <textarea rows="2" class="form-control" placeholder="Lorem ipsum dolor sit amet, consectetur adipisicing elit. Laboriosam, odit, quis animi expedita magnam mollitia quia alias unde voluptatibus eum laudantium suscipit nam hic explicabo ipsa dignissimos tempore enim voluptatem." disabled></textarea>
                            
                                
                                </div>
                              </div>
                                  <div class="modal-footer ">
                                      
                                <button type="button" class="btn btn-success btn-lg" style="width: 100%;" data-target="#Responder" data-toggle="tooltip" data-toggle="modal"><span class="glyphicon glyphicon-ok-sign"></span> Responder</button>
                              </div>
                                </div>
                            <!-- /.modal-content --> 
                          </div>
                              <!-- /.modal-dialog --> 
                            </div>
                        
                        <div class="modal fade" id="edit" tabindex="-1" role="dialog" aria-labelledby="edit" aria-hidden="true">
                              <div class="modal-dialog">
                            <div class="modal-content">
                                  <div class="modal-header">
                                <button type="button" class="close" data-dismiss="modal" aria-hidden="true"><span class="glyphicon glyphicon-remove" aria-hidden="true"></span></button>
                                <h4 class="modal-title custom_align" id="Heading">Responder Mensaje</h4>
                              </div>
                                <div class="modal-body">
                                <div class="form-group">
                                <label>Destinatario: </label>
                                <input class="form-control " type="text" value="Hugo Gutierrez" disabled>
                                </div>
                                <div class="form-group">
                                <label>Correo: </label>
                                <input class="form-control " type="text" value="hugo@fidei.mx" disabled>
                                </div>
                                <div class="form-group">
                                <label>Asunto: </label>
                                <input class="form-control " type="text" value="Problemas con mi cuenta" disabled>
                                </div>
                                <div class="form-group">
                                    <label>Mensaje: </label>
                                <textarea rows="2" class="form-control" placeholder="Mensaje"></textarea>
                            
                                
                                </div>
                              </div>
                                  <div class="modal-footer ">
                                <button type="button" class="btn btn-success"><span class="glyphicon glyphicon-ok-sign"></span> Enviar</button>
                                <button type="button" class="btn btn-danger" data-dismiss="modal"><span class="glyphicon glyphicon-remove" ></span> Cancelar</button>
                              </div>
                                </div>
                            <!-- /.modal-content --> 
                          </div>
                              <!-- /.modal-dialog --> 
                            </div>
                            
                            
                            
                            <div class="modal fade" id="delete" tabindex="-1" role="dialog" aria-labelledby="edit" aria-hidden="true">
                              <div class="modal-dialog">
                            <div class="modal-content">
                                  <div class="modal-header">
                                <button type="button" class="close" data-dismiss="modal" aria-hidden="true"><span class="glyphicon glyphicon-remove" aria-hidden="true"></span></button>
                                <h4 class="modal-title custom_align" id="Heading">Eliminar Mensaje</h4>
                              </div>
                                  <div class="modal-body">
                               
                               <div class="alert alert-danger"><span class="glyphicon glyphicon-warning-sign"></span> ¿Estás seguro que deseas eliminar éste mensaje?</div>
                               
                              </div>
                                <div class="modal-footer ">
                                <button type="button" class="btn btn-success" ><span class="glyphicon glyphicon-ok-sign"></span> Si</button>
                                <button type="button" class="btn btn-danger" data-dismiss="modal"><span class="glyphicon glyphicon-remove"></span> No</button>
                              </div>
                                </div>
                            <!-- /.modal-content --> 
                          </div>
                              <!-- /.modal-dialog --> 
                            </div>
                        </div>
                    </div>
                </div>
        </div>
    </div>
</div>

app/views/admin_panel/principal.html.erb
<div id="page-content-wrapper">
    <div class="page-content">
        <div class="container-fluid">
            <div class="container">
                <div class="row" style="margin-top: 70px;">
                    <h1 class="text-center" style="color: #004467;"><strong>PÁGINA PRINCIPAL</strong></h1>
                    <div class="row">
                        <div class="col-md-9">
                            <h3 class="text-center" style="color: #004467;"><strong>PAGO A PERSONAS</strong></h3>
                            <div class="col-md-6">
                              <div class="form-group">
                              <label for="exampleInputEmail1">Buscar No. Referencia</label>
                              <input type="text" class="form-control" id="" placeholder="Numero de Referencia">
                            </div>
                            </div>
                            <table class="table table-hover table-striped">
                              <tr style="background-color: #2c3e50; color: white;">
                                <th>ID Usuario</th>
                                <th>Nombre</th>
                                <th>Apellido</th>
                                <th>Monto a Pagar</th>
                                <th>Clabe Interbancaria</th>
                                <th></th>
                              </tr>
                             
                            </table>
                            <center><h2>Por el momento no hay pagos que realizar</h2></center>
                        </div>
                        <div class="col-md-3">
                            <h3 class="text-center" style="color: #004467;"><strong>TOTAL INGRESOS</strong></h3>
                            <div class="row">
                                <div class="col-xs-6">
                                  <label>Plan 1:</label>
                                  <input type="text" class="form-control" id="" value="<%= @p1.size %> Personas" disabled>
                                </div>
                                <div class="col-xs-6">
                                  <label>Plan 2:</label>
                                  <input type="text" class="form-control" id="" value="<%= @p2.size %> Personas" disabled>
                                </div>
                            </div></br>
                            <div class="row">
                                <div class="col-xs-6">
                                  <label>Plan 3:</label>
                                  <input type="text" class="form-control" id="" value="<%= @p3.size %> Personas" disabled>
                                </div>
                                <div class="col-xs-6">
                                  <label>Plan 4:</label>
                                  <input type="text" class="form-control" id=""value="<%= @p4.size %> Personas" disabled>
                                </div>
                            </div></br>
                        </div>
                    </div>
                      
                      
                </div>
            </div>
        </div>
    </div>
</div>

app/views/admin_panel/promotores.html.erb
<div id="page-content-wrapper">
        <div class="page-content">
            <div class="container-fluid">
              <div class="container">
                <div class="row" style="margin-top: 70px;">
                      <h1 class="text-center" style="color: #004467;"><strong>PROMOTORES</strong></h1>
                    
                       
                </div>
                </div>
                </div>
            </div>
        </div>
    </div>
</div>

app/views/admin_panel/validacion.html.erb
<div id="page-content-wrapper">
        <div class="page-content">
            <div class="container-fluid">
              <div class="container">
                  <div class="row" style="margin-top: 70px;">
                    <div class="col-md-offset-1">
                        <div class="col-md-11">
                            <h1 class="text-center" style="color: #004467;"><strong>VALIDACIÓN</strong></h1>
                            <div class="col-md-6">
                              <div class="form-group">
                              <label for="exampleInputEmail1">Buscar No. Referencia</label>
                              <input type="text" class="form-control" id="" placeholder="Numero de Referencia">
                            </div>
                            </div>
                            
                            
                            <table class="table table-hover table-striped">
                                <tr style="background-color: #2c3e50; color: white;">
                                    <th>ID Usuario</th>
                                    <th>Plan</th>
				    <th>Email</th>
                                    <th>Fecha de Inscripción</th>
                                    <th>No. Referencia</th>
                                    <th>Recibo</th>
                                    <th>Validar</th>
                                </tr> 
                              <% @payments.each do |p| %>
                                    <tr class="warning">
                                        <td><%= p.user_id %></td>
                                        <td>Plan <%= p.tipo_paquete %></td>
					 <td class="email<%=p.user_id%>">
                                          <script>
                                            $.get("<%= admin_panel_email_path %>",
                                                {
                                                    user_id: <%= p.user_id %>
                                                },
                                                function(data){
                                                  $(".email<%= p.user_id %>").html(data.email);
                                                });
                                          </script>
                                        </td>
                                        <td><%= p.created_at %></td>
                                        <td>
                                            <% if p.status == false  %>
                                                No validado
                                            <% end %>
                                        </td>
                                        <td>
                                            <button type="button" class="btn btn-info" data-ref="<%= p.avatar.url %>" data-toggle="modal" data-target="#myModal">
                                              Recibo
                                            </button>
                                        </td>
                                        <td>
                                            <%= link_to "Validar Pago.", admin_panel_validar_path(:payment_id => p.id, :tipo_paquete => p.tipo_paquete), data: { 
confirm: 'Estas seguro de validar este pago? Revisalo muy bien!' } ,:class => "btn btn-success btn-sm", :style => "margin-bottom: 33px, margin-top: 33px " %>
                                            <%= link_to "Rechazar Pago.", admin_panel_rechazar_path(:payment_id => p.id), data: { confirm: 'Estas seguro de 
rechazar este pago? Revisalo muy bien!' } ,:class => "btn btn-danger btn-sm", :style => "margin-bottom: 33px, margin-top: 33px " %>

                                        </td>
                                    </tr>
                              <% end %>
                            </table>
                            <% if @payments.size == 0 %>
                            <center><h2>Por el momento no hay pagos para validar.</h2></center>
                            <% end %>
                        </div>
                    </div>
                  </div>
                </div>
            </div>
        </div>
    </div>
</div>

<!-- Button trigger modal -->


<!-- Modal -->
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog modal-lg" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">Recibo Enviado</h4>
      </div>
      <div class="modal-body">
        ...
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>
<script>
  $('#myModal').on('show.bs.modal', function (event) {
    var button = $(event.relatedTarget) // Button that triggered the modal
    var recipient = button.data('ref') // Extract info from data-* attributes
    // If necessary, you could initiate an AJAX request here (and then do the updating in a callback).
    // Update the modal's content. We'll use jQuery here, but you could use a data binding library or other methods instead.
    var body = document.querySelector(".modal-body");
    body.innerHTML = `<img class="img-responsive" width="50%" src="${recipient}">`
  })
</script>