config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'
  
  # routes welcome
  get 'welcome/privacidad'
  get 'welcome/terminos'
  
  # route user_form_firebase
  get 'user_form_firebase/user_form'

  get 'user_form_firebase/changeFormStatus'

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }


  # routes user profile
  get 'user_profile/index'
  get 'user_profile/ajustes'
  get 'user_profile/validacion'
  get 'user_profile/update'
  get 'user_profile/ayuda'
  get 'user_profile/ficha'
  get 'user_profile/gFicha'
  get 'user_profile/rFicha'
  get 'user_profile/promotores'
  
  # routes admin_panel
  get 'admin_panel/index', path: 'admin_panel'
  get 'admin_panel/validacion'
  get 'admin_panel/reportes'
  get 'admin_panel/ayuda'
  get 'admin_panel/validar'
  get 'admin_panel/rechazar'
  get 'admin_panel/email'
  get 'admin_panel/showData'
  get 'admin_panel/usuarios'
  get 'admin_panel/promotores'
  
  
  resources :user_profile
  resources :user_settings
end

app/controllers/user_profile_controller.rb
class UserProfileController < ApplicationController
    before_action :user, only: [:index,:ajustes,:validacion,:ayuda,:gFicha,:ficha,:rFicha,:updatePayment,:update]
    
    

    def index
        @p1 = Payment.where(:user_id => current_user.id, :tipo_paquete => 1, :status => true )
	@c1 = Payment.where(:user_id => current_user.id, :tipo_paquete => 1 )
        @fcount1 = Array.new
        @p1.each do |p|
            positions1 = Array.new
            user = Arbol1.find_by(:payment_id => p.id, :user_id => p.user_id)

            start =  user.posicion
            @count1 = 0
            # Primer nivel debajo del inspeccionado
            positions1.push(left1 = start*2) # nivel 1 izquierdo
            positions1.push(right1 = left1+1) # niver 1 derecho
            
            # Segundo nivel debajo del inspeccionado
            positions1.push(left2_1 = left1*2) # nivel 2 primer izquierdo
            positions1.push(left2_2 = right1*2) # nivel 2 segundo izquierdo
            positions1.push(right2_1 = left2_1+1) # nivel 2 primer derecho
            positions1.push(right2_2 = left2_2+1) # nivel 2 segundo derecho
            
            # Tercer nivel debajo del inspeccionado
            positions1.push(left3_1 = left2_1*2) # nivel 3 primer izquierdo
            positions1.push(left3_2 = right2_1*2) # nivel 3 segundo inzquierdo
            positions1.push(left3_3 = left2_2*2) # nivel 3 tercer inzquierdo
            positions1.push(left3_4 = right2_2*2) # nivel 3 cuarto inzquierdo
            
            positions1.push(right3_1 = left3_1+1) # nivel 3 primer derecho
            positions1.push(right3_2 = left3_2+1) # nivel 3 segundo derecho
            positions1.push(right3_3 = left3_3+1) # nivel 3 tercer derecho
            positions1.push(right3_4 = left3_4+1) # nivel 3 cuarto derecho
	    
	    positions1.push(left4_1 = left3_1*2) # nivel 4 primer izquierdo
            positions1.push(left4_2 = right3_1*2) # nivel 4 segundo inzquierdo
            positions1.push(left4_3 = left3_2*2) # nivel 4 tercer inzquierdo
            positions1.push(left4_4 = right3_2*2) # nivel 4 cuarto inzquierdo
	    positions1.push(left4_5 = left3_3*2) # nivel 4 primer izquierdo
            positions1.push(left4_6 = right3_3*2) # nivel 4 segundo inzquierdo
            positions1.push(left4_7 = left3_4*2) # nivel 4 tercer inzquierdo
            positions1.push(left4_8 = right3_4*2) # nivel 4 cuarto inzquierdo


 
	    positions1.push(right4_1 = left4_1+1) # nivel 4 primer derecho
            positions1.push(right4_2 = left4_2+1) # nivel 4 segundo derecho
            positions1.push(right4_3 = left4_3+1) # nivel 4 tercer derecho
            positions1.push(right4_4 = left4_4+1) # nivel 4 cuarto derecho
	    positions1.push(right3_5 = left4_5+1) # nivel 4 quinto derecho
            positions1.push(right3_6 = left4_6+1) # nivel 4 sexto derecho
            positions1.push(right3_7 = left4_7+1) # nivel 4 septimo derecho
            positions1.push(right3_8 = left4_8+1) # nivel 4 octavo derecho
           
            positions1.each do |c|
                posExist = Arbol1.find_by(:posicion => c)
                if posExist
                    @count1+=1 
                end
            end
            @fcount1.push(@count1)
            
        end
        
        @p2 = Payment.where(:user_id => current_user.id, :tipo_paquete => 2, :status => true )
	@c2 = Payment.where(:user_id => current_user.id, :tipo_paquete => 2 )
        @fcount2 = Array.new
        @p2.each do |p|
            positions2 = Array.new
            user = Arbol2.find_by(:payment_id => p.id, :user_id => p.user_id)
            start =  user.posicion
            @count2 = 0
            # Primer nivel debajo del inspeccionado
            positions2.push(left1 = start*2) # nivel 1 izquierdo
            positions2.push(right1 = left1+1) # niver 1 derecho
            
            # Segundo nivel debajo del inspeccionado
            positions2.push(left2_1 = left1*2) # nivel 2 primer izquierdo
            positions2.push(left2_2 = right1*2) # nivel 2 segundo izquierdo
            positions2.push(right2_1 = left2_1+1) # nivel 2 primer derecho
            positions2.push(right2_2 = left2_2+1) # nivel 2 segundo derecho
            
            # Tercer nivel debajo del inspeccionado
            positions2.push(left3_1 = left2_1*2) # nivel 3 primer izquierdo
            positions2.push(left3_2 = right2_1*2) # nivel 3 segundo inzquierdo
            positions2.push(left3_3 = left2_2*2) # nivel 3 tercer inzquierdo
            positions2.push(left3_4 = right2_2*2) # nivel 3 cuarto inzquierdo
            
            positions2.push(right3_1 = left3_1+1) # nivel 3 primer derecho
            positions2.push(right3_2 = left3_2+1) # nivel 3 segundo derecho
            positions2.push(right3_3 = left3_3+1) # nivel 3 tercer derecho
            positions2.push(right3_4 = left3_4+1) # nivel 3 cuarto derecho
            
   	    positions2.push(left4_1 = left3_1*2) # nivel 4 primer izquierdo
            positions2.push(left4_2 = right3_1*2) # nivel 4 segundo inzquierdo
            positions2.push(left4_3 = left3_2*2) # nivel 4 tercer inzquierdo
            positions2.push(left4_4 = right3_2*2) # nivel 4 cuarto inzquierdo
            positions2.push(left4_5 = left3_3*2) # nivel 4 primer izquierdo
            positions2.push(left4_6 = right3_3*2) # nivel 4 segundo inzquierdo
            positions2.push(left4_7 = left3_4*2) # nivel 4 tercer inzquierdo
            positions2.push(left4_8 = right3_4*2) # nivel 4 cuarto inzquierdo



            positions2.push(right4_1 = left4_1+1) # nivel 4 primer derecho
            positions2.push(right4_2 = left4_2+1) # nivel 4 segundo derecho
            positions2.push(right4_3 = left4_3+1) # nivel 4 tercer derecho
            positions2.push(right4_4 = left4_4+1) # nivel 4 cuarto derecho
            positions2.push(right3_5 = left4_5+1) # nivel 4 quinto derecho
            positions2.push(right3_6 = left4_6+1) # nivel 4 sexto derecho
            positions2.push(right3_7 = left4_7+1) # nivel 4 septimo derecho
            positions2.push(right3_8 = left4_8+1) # nivel 4 octavo derecho

            positions2.each do |c|
                posExist = Arbol2.find_by(:posicion => c)
                if posExist
                    @count2+=1 
                end
            end
            @fcount2.push(@count2)
        end
        
        @p3 = Payment.where(:user_id => current_user.id, :tipo_paquete => 3, :status => true )
	@c3 = Payment.where(:user_id => current_user.id, :tipo_paquete => 3 )
        @fcount3 = Array.new
        @p3.each do |p|
            positions3 = Array.new
            user = Arbol3.find_by(:payment_id => p.id, :user_id => p.user_id)
            start =  user.posicion
            @count3 = 0
            # Primer nivel debajo del inspeccionado
            positions3.push(left1 = start*2) # nivel 1 izquierdo
            positions3.push(right1 = left1+1) # niver 1 derecho
            
            # Segundo nivel debajo del inspeccionado
            positions3.push(left2_1 = left1*2) # nivel 2 primer izquierdo
            positions3.push(left2_2 = right1*2) # nivel 2 segundo izquierdo
            positions3.push(right2_1 = left2_1+1) # nivel 2 primer derecho
            positions3.push(right2_2 = left2_2+1) # nivel 2 segundo derecho
            
            # Tercer nivel debajo del inspeccionado
            positions3.push(left3_1 = left2_1*2) # nivel 3 primer izquierdo
            positions3.push(left3_2 = right2_1*2) # nivel 3 segundo inzquierdo
            positions3.push(left3_3 = left2_2*2) # nivel 3 tercer inzquierdo
            positions3.push(left3_4 = right2_2*2) # nivel 3 cuarto inzquierdo
            
            positions3.push(right3_1 = left3_1+1) # nivel 3 primer derecho
            positions3.push(right3_2 = left3_2+1) # nivel 3 segundo derecho
            positions3.push(right3_3 = left3_3+1) # nivel 3 tercer derecho
            positions3.push(right3_4 = left3_4+1) # nivel 3 cuarto derecho
            
	    positions3.push(left4_1 = left3_1*2) # nivel 4 primer izquierdo
            positions3.push(left4_2 = right3_1*2) # nivel 4 segundo inzquierdo
            positions3.push(left4_3 = left3_2*2) # nivel 4 tercer inzquierdo
            positions3.push(left4_4 = right3_2*2) # nivel 4 cuarto inzquierdo
            positions3.push(left4_5 = left3_3*2) # nivel 4 primer izquierdo
            positions3.push(left4_6 = right3_3*2) # nivel 4 segundo inzquierdo
            positions3.push(left4_7 = left3_4*2) # nivel 4 tercer inzquierdo
            positions3.push(left4_8 = right3_4*2) # nivel 4 cuarto inzquierdo



            positions3.push(right4_1 = left4_1+1) # nivel 4 primer derecho
            positions3.push(right4_2 = left4_2+1) # nivel 4 segundo derecho
            positions3.push(right4_3 = left4_3+1) # nivel 4 tercer derecho
            positions3.push(right4_4 = left4_4+1) # nivel 4 cuarto derecho
            positions3.push(right3_5 = left4_5+1) # nivel 4 quinto derecho
            positions3.push(right3_6 = left4_6+1) # nivel 4 sexto derecho
            positions3.push(right3_7 = left4_7+1) # nivel 4 septimo derecho
            positions3.push(right3_8 = left4_8+1) # nivel 4 octavo derecho

            positions3.each do |c|
                posExist = Arbol3.find_by(:posicion => c)
                if posExist
                    @count3+=1 
                end
            end
            @fcount3.push(@count3)
        end
        
        @p4 = Payment.where(:user_id => current_user.id, :tipo_paquete => 4, :status => true )
	@c4 = Payment.where(:user_id => current_user.id, :tipo_paquete => 4 )
        @fcount4 = Array.new
        @p4.each do |p|
            positions4 = Array.new
            user = Arbol4.find_by(:payment_id => p.id, :user_id => p.user_id)
            start =  user.posicion
            @count4 = 0
            # Primer nivel debajo del inspeccionado

app/helpers/user_profile_helper.rb
module UserProfileHelper
end

app/views/user_profile/ayuda.html.erb
 <div class="container" style="margin-top: 75px;">
                      <h1 class="text-center" style="color: #004467;"><strong>¿NECESITAS AYUDA?</strong></h1>
                      <h2 class="text-center" style="color: #004467;">CONTÁCTANOS</h2></br>
              <div class="row">
                  <div class="col-md-9">
                          <form>
                          <div class="row">
                              <div class="col-md-6">
                                  <div class="form-group">
                                     <label for="">Asunto*</label>
                                     <select class="form-control" id="AyudaAsunto">
                                       <option hidden>Seleccionar Asunto</option>
                                       <option>Tengo problemas con mi cuenta</option>
                                       <option>No puedo cambiar mi información</option>
                                       <option>Quiero retirarme</option>
                                       <option>No he recibido mi bonificación</option>
                                       <option>No pude realizar el Pago</option>
                                       <option>No puedo realizar una nueva inversión</option>
                                       
                                     </select>
                                   </div>
                                  <div class="form-group">
                                      <label for="email">
                                          Correo Electrónico*</label>
                                      <div class="input-group">
                                          <span class="input-group-addon"><span class="glyphicon glyphicon-envelope"></span>
                                          </span>
                                          <input type="email" class="form-control" id="email_u" placeholder="Correo" required="required" value="martin@cocosource.com" disabled/></div>
                                  </div>
                                  
                                  <div class="row">
                                      <div class="col-md-6">
                                          <div class="form-group">
                                              <label for="subject">Telefono Fíjo*</label>
                                              <input type="text" class="form-control" id="TF_u" placeholder="Telefono" required="required" disabled/>
                                          </div>
                                      </div>
                                      <div class="col-md-6">
                                          <div class="form-group">
                                              <label for="subject">Telefono Móvil</label>
                                              <input type="text" class="form-control" id="TM_u" placeholder="Telefono" required="required" />
                                          </div>
                                      </div>
                                  </div>
                              </div>
                              <div class="col-md-6">
                                  <div class="form-group">
                                      <label for="name">Describe tu situación*</label>
                                      <textarea name="message" id="message" class="form-control" rows="9" cols="25" required="required" placeholder=""></textarea>
                                  </div>
                              </div>
                              <div class="col-md-12">
                                  <p style="text-align: right;"><button class="btn btn-hero btn-lg" role="button">Enviar</button></p>
                              </div>
                          </div>
                          </form>
                  </div>
                  <div class="col-md-3">
                      <form>
                        
                      <legend><span class="glyphicon glyphicon-globe"></span> Contacto</legend>
                      <address>
                          <strong>Correo Electrónico</strong><br>
                          <a href="mailto:#">contacto@fidei.mx</a>
                      </address>
                      </form>
                  </div>
              </div>
          </div>

app/views/user_profile/ficha.html.erb
<div class="container" style="margin-top: 75px;">
    <div class="row">
        <div class="col-md-12">
                <div class="FichaPago">
                   <h3>Ficha de Pago</h3>
                   <div class="contenedorFicha">
                       <%= image_tag("logofidei.png", :style => "width: 200px; margin: 10px;") %>
                       <div class="row" style="margin-bottom: 25px;">
                           <strong><h4>DATOS DE PAGO</h4></strong>
                           <div class="col-sm-12">
                               <label>BENEFICIARIO: </label> ENPRENMONEY S.A. DE C.V.</br>
                               <label>CUENTA:  </label> 7010 5047515</br>
                               <label>CLABE: </label> 002320701050475154 </br>
                           </div>
                       </div>
                       
                       <div class="row">
                           <div class="col-sm-12 fichita">
                               <h4 class="text-center">NUMERO DE REFERENCIA: <%= @np %></h4>
                           </div>
                       </div>
                       <div style="margin-bottom: 25px; margin-top: 25px;">
                       <div class="row">
                        <div class="col-sm-12">
                            <label>NOMBRE CLIENTE: </label><label class="textoFicha2" id="nombress"></label>
                        </div>
                       </div>
                       <div class="row">
                           <div class="col-sm-12">
                            <label>PLAN: </label>  <label class="textoFicha2"><%= @tipo %> </label>
                        </div>
                       </div>
                       <div class="row">
                           <div class="col-sm-12">
                            <label>FECHA DE GENERACION DE FICHA: </label> <label class="textoFicha2"><%= Date.today %>  </label>
                        </div>
                       </div>
                       </div>
                       <div class="row fichitados">
                        <div class="col-sm-12">
                            <label style="font-size: 16px;">TOTAL A</label> <label>PAGAR:</label> <label style="font-size: 16px;" class="textoFicha2">$ <%= @costo %></label>
                        </div>
                       </div>
                       </br>
                       <hr></br>
                       <label>Realiza tu Pago en:</label><br>
                       <center>
                           <%= image_tag("Banamex_Logo.png", :style => "width: 200px; margin: 10px;") %>
                       </center>
                       <br>
                       <label>*Importante: Antes de realizar tu deposito o transferencia, verifica que el concepto o giro del deposito sea el Numero de referencia que te otorgamos, cada referencia es única para cada pago.</label>
                       
                   </div>
                </div>
            </div>
    </div>
	<center>
		<button onClick="window.print()" class="btn btn-success">
		Imprimir PDF
		</button>
	</center>
</div>

<script>
        
	$(document).ready(function(){
	firebase_data_useer();

});    
    
    var firebase_data_useer = function firebase_data_useer(){
	
	firebase.auth().onAuthStateChanged(function(user) {
		if (user) {
			
	var commentsRef = firebase.database().ref('users/' + user.uid);
	commentsRef.on('value', function(data) {
		showdataa(data.val());
		
	});
		}
	});
	
}
var showdataa = function(data){
	$("#nombress").html(data.nombre+" "+data.apellidoP+" "+data.apellidoM);
}
</script>

app/views/user_profile/promotores.html.erb
<div id="page-content-wrapper">
        <div class="page-content">
            <div class="container-fluid">
              <div class="container">
                  <div class="row" style="margin-top: 70px;">
                  	<h1 class="text-center" style="color: #004467;"><strong>PANEL PROMOTOR</strong></h1><br>
                    <div class="col-md-4 col-md-offset-4">
				<div id="cardP" class="weater">
					<div class="city-selected">
						<article>

							<div class="info">
								<div class="city">Hugo Gutierrez</div>
								<div class="night"><span>Referencia:</span> XMDAOS9839</div>

						</article>
						
						<figure style="background-image: url(http://136.243.1.253/~creolitic/bootsnipp/home.jpg)"></figure>
					</div>

					<div class="days">
						<div class="row row-no-gutter">
							<div class="col-sm-4">
								<div class="day">
									<h1>Activos</h1>
									<label style="color: green;">10</label>
								</div>
							</div>

							<div class="col-sm-4">
								<div class="day">
									<h1>Pasivos</h1>
									<label style="color: red;">3</label>
								</div>
							</div>

							<div class="col-sm-4">
								<div class="day">
									<h1>Total</h1>
									<label>7</label>
								</div>
							</div>

						</div>
					</div>
					
					<div class="days">
						<div class="row row-no-gutter">
							<div class="col-sm-4">
								<div class="day">
									<h1>Activos</h1>
									<label style="color: green;">10</label>
								</div>
							</div>

							<div class="col-sm-4">
								<div class="day">
									<h1>Pasivos</h1>
									<label style="color: red;">3</label>
								</div>
							</div>

							<div class="col-sm-4">
								<div class="day">
									<h1>Total</h1>
									<label>7</label>
								</div>
							</div>

						</div>
					</div>
					
					<div class="days">
						<div class="row row-no-gutter">
							<div class="col-sm-4">
								<div class="day">
									<h1>Activos</h1>
									<label style="color: green;">10</label>
								</div>
							</div>

							<div class="col-sm-4">
								<div class="day">
									<h1>Pasivos</h1>
									<label style="color: red;">3</label>
								</div>
							</div>

							<div class="col-sm-4">
								<div class="day">
									<h1>Total</h1>
									<label>7</label>
								</div>
							</div>

						</div>
					</div>
					
					<div class="days">
						<div class="row row-no-gutter">
							<div class="col-sm-4">
								<div class="day">
									<h1>Activos</h1>
									<label style="color: green;">10</label>
								</div>
							</div>

							<div class="col-sm-4">
								<div class="day">
									<h1>Pasivos</h1>
									<label style="color: red;">3</label>
								</div>
							</div>

							<div class="col-sm-4">
								<div class="day">
									<h1>Total</h1>
									<label>7</label>
								</div>
							</div>

						</div>
					</div>
					
					<div class="days">
						<div class="row row-no-gutter">
							<div class="col-sm-4">
								<div class="day">
									<h1>Activos</h1>
									<label style="color: green;">10</label>
								</div>
							</div>

							<div class="col-sm-4">
								<div class="day">
									<h1>Pasivos</h1>
									<label style="color: red;">3</label>
								</div>
							</div>

							<div class="col-sm-4">
								<div class="day">
									<h1>Total</h1>
									<label>7</label>
								</div>
							</div>

						</div>
					</div>
					
					
					
					
				</div>
			</div>
                  </div>
                </div>
            </div>
        </div>
    </div>
</div>

app/views/user_profile/validacion.html.erb
<div id="page-content-wrapper">
        <div class="page-content">
            <div class="container-fluid">
              <div class="container">
                  <div class="row" style="margin-top: 20px;">
                    <div class="col-md-offset-1">
                        <div class="col-md-11">
                            <h1 class="text-center" style="color: #004467;"><strong>VALIDACIÓN</strong></h1>
                            <table class="table table-hover table-striped" data-no-turbolink="true">
                              <tr style="background-color: #2c3e50; color: white;">
                                <th>Plan</th>
                                <th>Fecha de Inscripción</th>
                                <th>Status</th>
				<th>PDF</th>
                                <th>Archivo</th>
                                <th>Validar</th>
                              </tr>
                              <% @payments.each do |p| %>
                                <tr class="
                                <% if p.status == false %>
                                    warning
                                    <% else %>
                                    success
                                    <% end %>
                                    
                                    ">
                                  <td>Plan <%= p.tipo_paquete %></td>
                                  <td><%= p.created_at %></td>
                                  <td>
                                    <% if p.rechazado == true  %>
                                      Rechazado, por favor revista tu correo electronico
                                    <% elsif p.status == true %>
                                      Activo
                                    <% elsif p.status == false  %>
                                      Pendiente por validar
                                    <% end %>
                                  </td>
				  <td>
				   <%=  link_to "Ver PDF", user_profile_rFicha_path(costo: p.costo, np: p.np, tipo_paquete: p.tipo_paquete), class: "btn 
btn-default", 
target: :_blank %>
				  </td>
                                  <td>
                                    <%= form_for p, url: user_profile_update_path, html: { multipart: true } do |form| %>
                                     
                                      <% if p.avatar_file_name != nil && p.rechazado == true%>
                                          <%= form.file_field :avatar, :class => "btn btn-default" %>
                                          <%= form.hidden_field :id, :value => p.id %>
                                          <%= form.hidden_field :rechazado, :value => false %>
                                       <% elsif p.avatar_file_name != nil %>
                                        <button type="button" class="btn btn-default" data-ref="<%= p.avatar.url %>" data-toggle="modal" data-target="#myModal">
                                          Recibo
                                        </button>
                                        <% elsif  p.avatar_file_name == nil%>
                                        <%= form.file_field :avatar, :class => "btn btn-default" %>
                                          <%= form.hidden_field :id, :value => p.id %>
                                          <%= form.hidden_field :rechazado, :value => false %>
                                      <% end %>  
                                  </td>
                                  <td>
                                     <% if p.avatar_file_name != nil && p.rechazado == true%>
                                        <%= form.submit 'Subir', :class => "submit-btn btn btn-default" %>
                                      <% elsif p.avatar_file_name != nil %>
                                        Enviado
                                      <% elsif p.avatar_file_name == nil %>  
                                        <%= form.submit 'Subir', :class => "submit-btn btn btn-default" %>
                                      <% end %>
                                    <% end %>
                                  </td>
                                </tr>
                              <% end %>
                             <!-- <tr class="info">
                                <td>Plan 1</td>
                                <td>18/05/2017</td>
                                <td>Activo</td>
                                <td><input type="button" class="btn btn-default" value="Imagen"></td>
                              </tr>
                              <tr class="danger">
                                <td>Plan 3</td>
                                <td>18/05/2017</td>
                                <td>Cancelado</td>
                                <td><input type="button" class="btn btn-default" value="Imagen"></td>
                              </tr>
                              <tr class="warning">
                                <td>Plan 4</td>
                                <td>18/05/2017</td>
                                <td>Sin Activar</td>
                                <td><input type="button" class="btn btn-default" value="Imagen"></td>
                              </tr>
                              <tr class="success">
                                <td>Plan 1</td>
                                <td>18/05/2017</td>
                                <td>Completado</td>
                                <td><input type="button" class="btn btn-default" value="Imagen"></td>
                              </tr>
                              <tr class="warning">
                                <td>Plan 2</td>
                                <td>18/05/2017</td>
                                <td>Sin Activar</td>
                                <td><input type="button" class="btn btn-default" value="Imagen"></td>
                              </tr>
                              <tr class="success">
                                <td>Plan 4</td>
                                <td>18/05/2017</td>
                                <td>Completado</td>
                                <td><input type="button" class="btn btn-default" value="Imagen"></td>
                              </tr> -->
                            </table>
                            <% if @payments.size == 0 %>
                            <h2 class="text-center">Aun no tienes ningun plan activado</h2>
                            <center><%= link_to "Invertir", user_profile_index_path, :class => "btn btn-primary btn-lg"%></center>
                            
                            <% end %>
                        </div>
                    </div>
                  </div>
                </div>
            </div>
        </div>
    </div>
</div>

<!-- Button trigger modal -->


<!-- Modal -->
<div class="modal fade " id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog modal-lg" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">Recibo Enviado</h4>
      </div>
      <div class="modal-body">
        ...
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>
<script>
  $('#myModal').on('show.bs.modal', function (event) {
    var button = $(event.relatedTarget) // Button that triggered the modal
    var recipient = button.data('ref') // Extract info from data-* attributes
    // If necessary, you could initiate an AJAX request here (and then do the updating in a callback).
    // Update the modal's content. We'll use jQuery here, but you could use a data binding library or other methods instead.
    var body = document.querySelector(".modal-body");
    body.innerHTML = `<img class="img-responsive" src="${recipient}">`
  })
  document.addEventListener('turbolinks:load',function(){
    $('.submit-btn').on('click',function(){
      $('form').submit()
    });
  });
    

  
 
</script>