config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'
  
  # routes welcome
  get 'welcome/privacidad'
  get 'welcome/terminos'
  
  # route user_form_firebase
  get 'user_form_firebase/user_form'

  get 'user_form_firebase/changeFormStatus'

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }


  # routes user profile
  get 'user_profile/index'
  get 'user_profile/ajustes'
  get 'user_profile/validacion'
  get 'user_profile/update'
  get 'user_profile/ayuda'
  get 'user_profile/ficha'
  get 'user_profile/gFicha'
  get 'user_profile/rFicha'
  get 'user_profile/promotores'
  
  # routes admin_panel
  get 'admin_panel/index', path: 'admin_panel'
  get 'admin_panel/validacion'
  get 'admin_panel/reportes'
  get 'admin_panel/ayuda'
  get 'admin_panel/validar'
  get 'admin_panel/rechazar'
  get 'admin_panel/email'
  get 'admin_panel/showData'
  get 'admin_panel/usuarios'
  get 'admin_panel/promotores'
  
  
  resources :user_profile
  resources :user_settings
end

app/models/ability.rb
class Ability
  include CanCan::Ability
 
  def initialize(user)
    # Define abilities for the passed in user here. For example:
 
    user ||= User.new # guest user (not logged in)
    if user.superadmin_role?
      can :manage, :all
    end
    if user.supervisor_role?
      can :manage, User
    end
    
  end
end

app/models/arbol1.rb
class Arbol1 < ActiveRecord::Base

end

app/models/arbol2.rb
class Arbol2 < ActiveRecord::Base
end

app/models/arbol3.rb
class Arbol3 < ActiveRecord::Base
end

app/models/arbol4.rb
class Arbol4 < ActiveRecord::Base
end

app/models/p1.rb
class P1 < ActiveRecord::Base
end

app/models/p2.rb
class P2 < ActiveRecord::Base
end

app/models/p3.rb
class P3 < ActiveRecord::Base
end

app/models/p4.rb
class P4 < ActiveRecord::Base
end

app/models/payment.rb
class Payment < ActiveRecord::Base


    validates :avatar,
    attachment_content_type: { content_type: /\Aimage\/.*\Z/ },
    attachment_size: { less_than: 15.megabytes }

  has_attached_file :avatar,
    :storage => :cloudinary,
    :path => "payments/:filename",
    :styles => {
      :thumb => '600x600>',
      :square => '800x800#',
      :medium => '1200x1200>'
    }
end

app/models/user.rb
class User < ActiveRecord::Base
  
 
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable #, :confirmable
         
   validates :avatar,
    attachment_content_type: { content_type: /\Aimage\/.*\Z/ },
    attachment_size: { less_than: 15.megabytes }

  has_attached_file :avatar,
    :storage => :cloudinary,
    :path => "avatar/:filename",
    :styles => {
      :thumb => '600x600>',
      :square => '800x800#',
      :medium => '1200x1200>'
    }
end

app/controllers/session_controller.rb
class SessionController < ApplicationController
    def index
        
    end
    
    def new 
        
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  before_action :user, only: [:index,:terminos,:privacidad]
  def user
        if current_user
        
        @id = current_user.id
        end
  end

  def index
    
    
  end
  
  def terminos
    render 'terminos'
  end
  
  def privacidad
    render 'privacidad'
  end
  

end

app/helpers/admin_panel_helper.rb
module AdminPanelHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/session_helper.rb
module SessionHelper
end

app/helpers/user_form_firebase_helper.rb
module UserFormFirebaseHelper
end

app/helpers/user_profile_helper.rb
module UserProfileHelper
end

app/helpers/user_settings_helper.rb
module UserSettingsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/_nav.html.erb
        

        <nav class="navbar navbar-fixed-top" data-turbolinks-permanent>
          <input type="hidden" value="<%= @id %>" id="id_user_to_data"></input>
          <div  style="background-color: #2c3e50 ; padding-bottom: 15px; padding-top: 15px;">
          <div class="container-fluid">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
              <button type="button" class="navbar-toggle collapsed btn-lg" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
              <span class="glyphicon glyphicon-menu-hamburger" style="color: white;"></span>
              </button>
              <a class="navbar-brand" href="..">
                
                <%= image_tag("logo.png", :style => "width: 150px; margin-top: -20px;", :class => "img-responsive") %>
                </a>
            </div>
        
            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
              <ul class="nav navbar-nav">
                <li><a class="linksop" href="../../#sEmpresa">Empresa</a></li>
                <li><a class="linksop" href="../../#sOperacion">Forma de Operación</a></li>
                <li><a class="linksop" href="../../#sInfo">Información</a></li>
                <li><a class="linksop" href="../../#sPlan">Planes</a></li>
                <li><a class="linksop" href="../../#sContacto">Contacto</a></li>
              </ul>
              <ul class="nav navbar-nav navbar-right">
                
                <li class="dropdown">
                  <a class="dropdown-toggle linksop" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                    <% if user_signed_in? %>
                    <span id="nombres"></span><span id="apellidos"></span>
                    <% else %>
                    <i class="glyphicon glyphicon-user"></i>
                    <% end %>
                    <span class="caret"></span></a>
                  			<ul id="login-dp" class="dropdown-menu" style="background-color: #2c3e50">
                  			  <% if user_signed_in? %>
                  			  <div class="Top text-center">
                  			    <li class="btn" style="padding: 30px;">
                  			     <% if current_user.supervisor_role? %>
                  			     <%= link_to "Mi Panel", admin_panel_index_path, :class => "logStyle", :style => "padding: 10px;" %>
                  			     <% else %>
                  			     <%= link_to "Mi Panel", user_profile_index_path, :class => "logStyle", :style => "padding: 10px;" %>
                  			     <% end %>
                  			    </li>
                  			    <br></br>
                  			    <li>
                  			    <%= link_to 'Cerrar Sesion', destroy_user_session_path, :method => :delete, :class => "logStyle", :style => "padding: 10px;" %>
                  			    </li>
                          <% else %>

                          <li class="text-center"><%= link_to 'Iniciar Sesión', new_user_session_path, :class => "linkhover", :style => "padding: 10px; color: white;" %></li>
                          <li class="text-center"><%= link_to 'Registrarse', new_user_registration_path, :class => "linkhover", :style => "padding: 10px; margin-bottom: 10px; color: white;" %></li>
                        <!--  <li>-->
                          
                        <!--  <div class="row">-->
                  					 <!--  <div class="Top text-center">-->
                  					 <!--    <a href="../users/sign_in" class="logStyle">-->
                  					 <!--     <h4><i class="glyphicon glyphicon-user"></i> INICIO DE SESIÓN</h4>-->
                  					 <!--    </a>-->
                  						<!--	</div>-->
                  						<!--	<div class="col-md-12">-->
                        <!--          </br>-->
                  								 
                  
                  						<!--				<div class="form-group">-->
                  						<!--					 <label class="sr-only" for="exampleInputEmail2">Correo Electrónico</label>-->
                  						<!--					 <input type="email" class="form-control" id="email" placeholder="Email" required>-->
                  						<!--				</div>-->
                  						<!--				<div class="form-group">-->
                  						<!--					 <label class="sr-only" for="exampleInputPassword2">Contraseña</label>-->
                  						<!--					 <input type="password" class="form-control" id="password" placeholder="Contraseña" required>-->
                        <!--                                       <div class="help-block text-right"><a href="">¿Olvidaste tu Contaseña?</a></div>-->
                  						<!--				</div>-->
                  						<!--				<div class="form-group">-->
                  
                  						<!--					 <button onClick="logIn()" class="btn btn-hero btn-block">Inciar Sesion</button>-->
                  
                  											 
                  
                  						<!--				</div>-->
                  						<!--				<div class="checkbox">-->
                  						<!--					 <label>-->
                  						<!--					 <input type="checkbox"> Recordar Contraseña-->
                  						<!--					 </label>-->
                  						<!--				</div>-->
                  								
                  						<!--	</div>-->
                  						<!--	<div class="bottom text-center">-->
                  						<!--		¿Eres Nuevo? <%= link_to 'Registrate ahora.', '../users/sign_up' %>  -->
                  						<!--	</div>-->
                  					 <!--</div>-->
                          
                        <!--  </li>-->
                          <% end %>
                  			</ul>

                  <!--<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Inicio de Sesión<span class="caret"></span></a>-->
                  <!--<ul class="dropdown-menu">
                    <% if user_signed_in? %>
                      <li>
                      <%= link_to('Logout', destroy_user_session_path, :method => :delete) %>        
                      </li>
                    <% else %>
                      <li>
                      <%= link_to('Login', new_user_session_path)  %>  
                      </li>
                    <% end %>
                  </ul>-->
                </li>
              </ul>
              </div>
              </div>
            </div><!-- /.navbar-collapse -->
          </div><!-- /.container-fluid -->
        </nav>
                  

app/views/layouts/_navAdminDos.html.erb
<div id="wrapper">
    <nav class="navbar navbar-fixed-top" role="navigation">
      <div  style="background-color: #273746; padding-bottom: 15px; padding-top: 15px;">
		<div class="container-fluid">
			<div class="navbar-header">
                <div  class="navbar-brand">
                    <p id="menu-toggle" style="color: white;" class="glyphicon glyphicon-menu-hamburger btn-menu toggle" onclick="openNav()">
                    </p>
    				<%= link_to image_tag("logo.png", :style => "width: 150px; margin-top: -20px;"), admin_panel_index_path %>
                </div>
			</div>
		</div>
		</div>
	</nav>
	
	
	<div id="mySidenav" class="sidenav" data-turbolinks-permanent>
	  <a href="javascript:void(0)" class="closebtn" onclick="closeNav()">&times;</a>
	  
	  <nav id="spy">
            <div class="profile-sidebar">
				<div class="profile-userpic">
					<%= image_tag("http://api.adorable.io/avatar/"+(rand(1..100)).to_s , :style => "display:block; margin:auto;") %>
				</div>
				<div class="profile-usertitle">
					<div class="profile-usertitle-name">
						<span id="nombres"></span></br>
						<span id="apellidos"></span>
					</div>
					<div class="profile-usertitle-job">
						<span id="emails"></span>
					</div>
				</div>

				<div class="profile-userbuttons">
					<%= link_to 'Cerrar Sesion', destroy_user_session_path, :method => :delete, :class =>  "btn btn-danger btn-sm", :onClick => "signOut()", :style => "color: white;" %>      
				</div>
				<div class="profile-usermenu">
					<ul class="nav">
						<li class="qwert active">
						    <%= link_to " Principal", {controller: "admin_panel", action: "index"}, class: "glyphicon glyphicon-home", :onClick => "closeNav()" %>
							<!--<a href="#">-->
							<!--<i class="glyphicon glyphicon-home"></i>-->
							<!--Principal </a>-->
						</li>
						<li class="qwert">
						    <%= link_to " Usuarios", {controller: "admin_panel", action: "usuarios"}, class: "glyphicon glyphicon-user", :onClick => "closeNav()"%>
							<!--<a href="#">-->
							<!--<i class="glyphicon glyphicon-flag"></i>-->
							<!--Ayuda </a>-->
						</li>
						<li class="qwert">
						    <%= link_to " Validacion", {controller: "admin_panel", action: "validacion"}, class: "glyphicon glyphicon-ok",  :onClick => "closeNav()"%>
							<!--<a href="#" target="_blank">-->
							<!--<i class="glyphicon glyphicon-ok"></i>-->
							<!--Validación </a>-->
						</li>
						<li class="qwert">
						    <%= link_to " Promotores", {controller: "admin_panel", action: "promotores"}, class: "glyphicon glyphicon-briefcase", :onClick => "closeNav()"%>
							<!--<a href="#">-->
							<!--<i class="glyphicon glyphicon-flag"></i>-->
							<!--Ayuda </a>-->
						</li>
						<li class="qwert">
						    <%= link_to " Reportes", {controller: "admin_panel", action: "reportes"}, class: "glyphicon glyphicon-stats" , :onClick => "closeNav()"%>
							<!--<a href="#">-->
							<!--<i class="glyphicon glyphicon-user"></i>-->
							<!--Ajustes</a>-->
						</li>
						<li class="qwert">
						    <%= link_to " Mensajes", {controller: "admin_panel", action: "ayuda"}, class: "glyphicon glyphicon-flag", :onClick => "closeNav()"%>
							<!--<a href="#">-->
							<!--<i class="glyphicon glyphicon-flag"></i>-->
							<!--Ayuda </a>-->
						</li>
					</ul>
				</div>
			</div>
        </nav>
	</div>
	
<script>
  /* Set the width of the side navigation to 250px */
function openNav() {
    document.getElementById("mySidenav").style.width = "250px";
}

/* Set the width of the side navigation to 0 */
function closeNav() {
    document.getElementById("mySidenav").style.width = "0";
}
</script>

app/views/layouts/_navProvisional.html.erb
<nav class="navbar navbar-fixed-top" data-turbolinks-permanent>
          <div  style="background-color: #2c3e50 ; padding-bottom: 15px; padding-top: 15px;">
          <div class="container-fluid">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
              <button type="button" class="navbar-toggle collapsed btn-lg" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
              <span class="glyphicon glyphicon-menu-hamburger" style="color: white;"></span>
              </button>
              <a class="navbar-brand" href="..">
                
                <%= image_tag("logo.png", :style => "width: 150px; margin-top: -20px;", :class => "img-responsive") %>
                </a>
            </div>
        
            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
              <ul class="nav navbar-nav">
                <li><a class="linksop" href="../../">Inicio</a></li>
                <!--<li><a class="linksop" href="../../#sProyeccion">Proyección</a></li>-->
                <li><a class="linksop" href="../../#sOperacion">Forma de Operación</a></li>
                <li><a class="linksop" href="../../#sInfo">Información</a></li>
                <li><a class="linksop" href="../../#sPlan">Planes</a></li>
                <li><a class="linksop" href="../../#sEmpresa">Empresa</a></li>
                <li><a class="linksop" href="../../#sContacto">Contacto</a></li>
              </ul>
            </div><!-- /.navbar-collapse -->
          </div><!-- /.container-fluid -->
                  </div>
        </nav>

app/views/layouts/_navUserDos.html.erb
<div id="wrapper">
    <nav class="navbar navbar-fixed-top" role="navigation">
      <div  style="background-color: #273746; padding-bottom: 15px; padding-top: 15px;">
		<div class="container-fluid">
			<div class="navbar-header">
                <div  class="navbar-brand">
                    <p id="menu-toggle" style="color: white;" class="glyphicon glyphicon-menu-hamburger btn-menu toggle" onclick="openNav()">
                    </p>
    				<%= link_to image_tag("logo.png", :style => "width: 150px; margin-top: -20px;"), user_profile_index_path %>
                </div>
			</div>
		</div>
		</div>
	</nav>
	
	<div id="mySidenav" class="sidenav" data-turbolinks-permanent>
	  <a href="javascript:void(0)" class="closebtn" onclick="closeNav()">&times;</a>
	  <nav id="spy">
            <div class="profile-sidebar">
				<div class="profile-userpic">
					<% if current_user.avatar_file_name != nil %>
						<%= image_tag current_user.avatar.url, :style => "display:block; margin:auto;" %>
					<% else %>
						<%= image_tag("http://api.adorable.io/avatar/"+(rand(1..100)).to_s , :style => "display:block; margin:auto;") %>
					<% end %>
				</div>
				<div class="profile-usertitle">
					<div class="profile-usertitle-name">
						<span id="nombres"></span></br>
						<span id="apellidos"></span>
					</div>
					<div class="profile-usertitle-job">
						<span id="emails"></span>
					</div>
				</div>

				<div class="profile-userbuttons">
					<%= link_to 'Cerrar Sesion', destroy_user_session_path, :method => :delete, :class =>  "btn btn-danger btn-sm", :onClick => "signOut()", :style => "color: white;" %>      
				</div>
				<div class="profile-usermenu">
					<ul class="nav">
						<li class="qwert active">
						    <%= link_to " Principal", {controller: "user_profile", action: "index"}, class: "glyphicon glyphicon-home", :onClick => "closeNav()" %>
							<!--<a href="#">-->
							<!--<i class="glyphicon glyphicon-home"></i>-->
							<!--Principal </a>-->
						</li>
						<li class="qwert ">
						    <%= link_to " Ajustes", {controller: "user_profile", action: "ajustes"}, class: "glyphicon glyphicon-user", :onClick => "closeNav()" %>
							<!--<a href="#">-->
							<!--<i class="glyphicon glyphicon-user"></i>-->
							<!--Ajustes</a>-->
						</li>
						<li class="qwert ">
						    <%= link_to " Validacion", {controller: "user_profile", action: "validacion"}, class: "glyphicon glyphicon-ok", :onClick => "closeNav()" %>
							<!--<a href="#" target="_blank">-->
							<!--<i class="glyphicon glyphicon-ok"></i>-->
							<!--Validación </a>-->
						</li>
						<li class="qwert ">
						    <%= link_to " Ayuda", {controller: "user_profile", action: "ayuda"}, class: "glyphicon glyphicon-flag", :onClick => "closeNav()"%>
							<!--<a href="#">-->
							<!--<i class="glyphicon glyphicon-flag"></i>-->
							<!--Ayuda </a>-->
						</li>
						<li class="qwert ">
						    <%= link_to " Promotores", {controller: "user_profile", action: "promotores"}, class: "glyphicon glyphicon-briefcase", :onClick => "closeNav()"%>
							<!--<a href="#">-->
							<!--<i class="glyphicon glyphicon-flag"></i>-->
							<!--Ayuda </a>-->
						</li>
					</ul>
				</div>
			</div>
        </nav>
	</div>

	
	
	
	

    <input type="hidden" value="<%= @id %>" id="id_user_to_data"></input>
    
    
<script>
  /* Set the width of the side navigation to 250px */
function openNav() {
    document.getElementById("mySidenav").style.width = "250px";
}

/* Set the width of the side navigation to 0 */
function closeNav() {
    document.getElementById("mySidenav").style.width = "0";
}
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>FIDEI</title>
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<meta name="google-site-verification" content="6TzyOjW-SgAwqUqWBaQw9_47ciW9MlwrwjtW_Fw_rZo" />
	<!-- FontAwesome -->
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
	<%= favicon_link_tag 'favicon.png' %>

	<link href="//maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet">
	<meta name="turbolinks-cache-control" content="no-cache">

	<% unless flash.empty? %>
	<script type="text/javascript">
		<% flash.each do |f| %>
		<% type = f[0].to_s.gsub('alert', 'error').gsub('notice', 'info') %>
		toastr['<%= type %>']('<%= f[1] %>');
		<% end %>
	</script>
	<% end %>
	
	

  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %> 
  <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.5.0/Chart.bundle.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.5.0/Chart.js"></script>
	
	<!--CDN FIREBASE-->
	
<script src="https://www.gstatic.com/firebasejs/4.1.3/firebase.js"></script>
<script>
  // Initialize Firebase
  var config = {
    apiKey: "AIzaSyA6OL-zRhqlAwzwCTK_eZ1_Gb4KIPhjA2c",
    authDomain: "fidei-df894.firebaseapp.com",
    databaseURL: "https://fidei-df894.firebaseio.com",
    projectId: "fidei-df894",
    storageBucket: "fidei-df894.appspot.com",
    messagingSenderId: "717833398004"
  };
  firebase.initializeApp(config);
</script>
</head>
<body style="background-color: #fcf7f7; position: relative;">

<!--Navbar de users_profile-->
<% if(controller.controller_name == "user_profile") %>
 <%= render 'layouts/navUserDos.html.erb' %>
<% end %>

<!--Navbar de admin_panel-->
<% if (controller.controller_name == "admin_panel") %>
<%= render 'layouts/navAdminDos.html.erb' %>
<% end %>

<% if((controller.controller_name == "welcome")) %>
<%= render 'layouts/nav.html.erb' %>
<% end %>

<% if((controller.controller_name == "users")) %>
<%= render 'layouts/nav.html.erb' %>
<% end %>


	<div class="main-container">
		<%= yield %>
	</div>

</body>
</html>